/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.redesordinario;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author togae
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setImagenMapa();
        jButtonMapaBusqueda.setVisible(false);
        jComboBoxUbicacion.setVisible(false);
        jComboBoxDestino.setVisible(false);
        setImagenWeb();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Icon.png")));
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jToggleButton1 = new javax.swing.JToggleButton();
        jComboBoxUbicacion = new javax.swing.JComboBox<>();
        jComboBoxDestino = new javax.swing.JComboBox<>();
        jTextFieldBarraBusqueda = new javax.swing.JTextField();
        jButtonSalida = new javax.swing.JButton();
        jButtonMapa = new javax.swing.JButton();
        jButtonPerros = new javax.swing.JButton();
        jButtonVideos = new javax.swing.JButton();
        jButtonNoticias = new javax.swing.JButton();
        jButtonMapaBusqueda = new javax.swing.JButton();
        jScrollPaneVistaResultados = new javax.swing.JScrollPane();
        jListResultados = new javax.swing.JList<>();
        jLabelimageWeeb = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxUbicacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SALTILLO", "TORREON", "MONCLOVA", "PIEDRAS NEGRAS", "MATAMOROS", "RAMOS ARIZPE", "PARRAS DE LA FUENTE", "SAN PEDRO", "GENERAL CEPEDA", "SABINAS", "ZARAGOZA", "SACRAMENTO", "MORELOS", "OCAMPO", "ARTEAGA", "ABASOLO" }));
        jComboBoxUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUbicacionActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 520, 40));

        jComboBoxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SALTILLO", "TORREON", "MONCLOVA", "PIEDRAS NEGRAS", "MATAMOROS", "RAMOS ARIZPE", "PARRAS DE LA FUENTE", "SAN PEDRO", "GENERAL CEPEDA", "SABINAS", "ZARAGOZA", "SACRAMENTO", "MORELOS", "OCAMPO", "ARTEAGA", "ABASOLO" }));
        getContentPane().add(jComboBoxDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 520, 40));

        jTextFieldBarraBusqueda.setFont(new java.awt.Font("SansSerif", 2, 24)); // NOI18N
        jTextFieldBarraBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBarraBusquedaActionPerformed(evt);
            }
        });
        jTextFieldBarraBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBarraBusquedaKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldBarraBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 520, 40));

        jButtonSalida.setBackground(new java.awt.Color(255, 51, 51));
        jButtonSalida.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButtonSalida.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalida.setText("X");
        jButtonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 70, 40));

        jButtonMapa.setBackground(new java.awt.Color(51, 51, 51));
        jButtonMapa.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonMapa.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMapa.setText("Mapa");
        jButtonMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMapaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        jButtonPerros.setBackground(new java.awt.Color(51, 51, 51));
        jButtonPerros.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonPerros.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPerros.setText("Perros");
        jButtonPerros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerrosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPerros, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jButtonVideos.setBackground(new java.awt.Color(51, 51, 51));
        jButtonVideos.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonVideos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVideos.setText("Videos");
        jButtonVideos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVideosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVideos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jButtonNoticias.setBackground(new java.awt.Color(51, 51, 51));
        jButtonNoticias.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonNoticias.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNoticias.setText("Noticias");
        jButtonNoticias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoticiasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNoticias, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jButtonMapaBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMapaBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMapaBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 70, 60));

        jListResultados.setBackground(new java.awt.Color(51, 51, 51));
        jListResultados.setFont(new java.awt.Font("SansSerif", 2, 24)); // NOI18N
        jListResultados.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPaneVistaResultados.setViewportView(jListResultados);

        getContentPane().add(jScrollPaneVistaResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 770, 350));
        getContentPane().add(jLabelimageWeeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 110, 100));

        jLabelFondo.setBackground(new java.awt.Color(42, 59, 71));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBarraBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBarraBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBarraBusquedaActionPerformed

    private void jButtonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalidaActionPerformed

    private void jTextFieldBarraBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBarraBusquedaKeyTyped
        char tecla = evt.getKeyChar();
        if (tecla == KeyEvent.VK_ENTER) {
            
            API_Noticias n = new API_Noticias(jTextFieldBarraBusqueda.getText());
            setResultados(n.toListString());
        }
    }//GEN-LAST:event_jTextFieldBarraBusquedaKeyTyped

    private void jButtonMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMapaActionPerformed
        jTextFieldBarraBusqueda.setVisible(false);
        jButtonMapaBusqueda.setVisible(true);
        jComboBoxUbicacion.setVisible(true);
        jComboBoxDestino.setVisible(true);
    }//GEN-LAST:event_jButtonMapaActionPerformed

    private void jButtonPerrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerrosActionPerformed
        jTextFieldBarraBusqueda.setVisible(true);
        jButtonMapaBusqueda.setVisible(false);
        jComboBoxUbicacion.setVisible(false);
        jComboBoxDestino.setVisible(false);
        API_Perros p = new API_Perros(jTextFieldBarraBusqueda.getText());
        setResultados(p.toListString());
    }//GEN-LAST:event_jButtonPerrosActionPerformed

    private void jButtonVideosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVideosActionPerformed
        jTextFieldBarraBusqueda.setVisible(true);
        jButtonMapaBusqueda.setVisible(false);
        jComboBoxUbicacion.setVisible(false);
        jComboBoxDestino.setVisible(false);
        API_YouTube y = new API_YouTube(jTextFieldBarraBusqueda.getText());
        setResultados(y.toListString());
    }//GEN-LAST:event_jButtonVideosActionPerformed

    private void jButtonNoticiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoticiasActionPerformed
        jTextFieldBarraBusqueda.setVisible(true);
        jButtonMapaBusqueda.setVisible(false);
        jComboBoxUbicacion.setVisible(false);
        jComboBoxDestino.setVisible(false);
        API_Noticias n = new API_Noticias(jTextFieldBarraBusqueda.getText());
        setResultados(n.toListString());
    }//GEN-LAST:event_jButtonNoticiasActionPerformed

    private void jComboBoxUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUbicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUbicacionActionPerformed

    private void jButtonMapaBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMapaBusquedaActionPerformed
        String ubicacion = String.valueOf(jComboBoxUbicacion.getSelectedItem());
        String destino = String.valueOf(jComboBoxDestino.getSelectedItem());
        
        Ubicaciones u = new Ubicaciones(latitud(ubicacion),longitud(ubicacion),latitud(destino),longitud(destino));
        double hr = u.haversine()/100;
        List<String> aux = new ArrayList<String>();
        aux.add("Ubicacion actual: "+ubicacion);
        aux.add("Destino: "+destino);
        aux.add("La ruta mas rapida para llegar a "+destino+" se encuentra a "+u.haversine()+" kilometros");
        aux.add("Tiempo estimado para llegar a "+destino+" a una velociadad de 100 km/h es de "+hr+" horas");
        
        setResultados(aux);
    }//GEN-LAST:event_jButtonMapaBusquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    public void setResultados(List<String> resultados) {
        DefaultListModel<String> modelo = new DefaultListModel<>();

        for (int i = 0; i < resultados.size(); i++) {
            modelo.addElement(resultados.get(i));
        }
        jListResultados.setModel(modelo);
    }

    public void setImagenWeb() {
        ImageIcon foto = new ImageIcon("src/main/resources/Imagenes/Web.png");
        Icon icon = new ImageIcon(foto.getImage().getScaledInstance(jLabelimageWeeb.getWidth(), jLabelimageWeeb.getHeight(), Image.SCALE_DEFAULT));
        jLabelimageWeeb.setIcon(icon);
        this.repaint();
    }

    public void setImagenMapa() {
        ImageIcon foto = new ImageIcon("src/main/resources/Imagenes/mapa.png");
        Icon icon = new ImageIcon(foto.getImage().getScaledInstance(jButtonMapaBusqueda.getWidth(), jButtonMapaBusqueda.getHeight(), Image.SCALE_DEFAULT));
        jButtonMapaBusqueda.setIcon(icon);
        jButtonMapaBusqueda.setFocusPainted(false);
        jButtonMapaBusqueda.setBorderPainted(false);
        jButtonMapaBusqueda.setContentAreaFilled(false);
        this.repaint();
    }
    
    public double latitud(String municipio){
        double latitud = 0;
        switch(municipio){
            case "SALTILLO": latitud = 25.42321;break;
            case "TORREON": latitud = 25.54389;break;
            case "MONCLOVA": latitud =  26.9687;break;
            case "PIEDRAS NEGRAS": latitud = 28.7007;break;
            case "MATAMOROS": latitud =  25.52699;break;
            case "RAMOS ARIZPE": latitud = 25.53928;break;
            case "PARRAS DE LA FUENTE": latitud = 25.44185;break;
            case "SAN PEDRO": latitud = 25.75602;break;
            case "GENERAL CEPEDA": latitud = 25.37767;break;
            case "SABINAS": latitud = 27.85591;break;
            case "ZARAGOZA": latitud = 28.4932;break;
            case "SACRAMENTO": latitud = 27.00264;break;
            case "MORELOS": latitud = 28.40676;break;
            case "OCAMPO": latitud = 27.31475;break;
            case "ARTEAGA": latitud = 25.44528;break;
            case "ABASOLO": latitud = 27.18219;break;
        }
        return latitud;
    }
    
    public double longitud(String municipio){
        double longitud = 0;
        switch(municipio){
            case "SALTILLO": longitud = -101.0053;break;
            case "TORREON": longitud = -103.41898;break;
            case "MONCLOVA": longitud =  -101.4205;break;
            case "PIEDRAS NEGRAS": longitud = -100.52353;break;
            case "MATAMOROS": longitud =  -103.2285;break;
            case "RAMOS ARIZPE": longitud = -100.94742;break;
            case "PARRAS DE LA FUENTE": longitud = -102.17808;break;
            case "SAN PEDRO": longitud = -102.98385;break;
            case "GENERAL CEPEDA": longitud = -101.47571;break;
            case "SABINAS": longitud = -101.11738;break;
            case "ZARAGOZA": longitud = -100.9223;break;
            case "SACRAMENTO": longitud = -101.72463;break;
            case "MORELOS": longitud = -100.88854;break;
            case "OCAMPO": longitud = -102.3966;break;
            case "ARTEAGA": longitud = -100.84667;break;
            case "ABASOLO": longitud = -101.42757;break;
        }
        return longitud;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMapa;
    private javax.swing.JButton jButtonMapaBusqueda;
    private javax.swing.JButton jButtonNoticias;
    private javax.swing.JButton jButtonPerros;
    private javax.swing.JButton jButtonSalida;
    private javax.swing.JButton jButtonVideos;
    private javax.swing.JComboBox<String> jComboBoxDestino;
    private javax.swing.JComboBox<String> jComboBoxUbicacion;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelimageWeeb;
    private javax.swing.JList<String> jListResultados;
    private javax.swing.JScrollPane jScrollPaneVistaResultados;
    private javax.swing.JTextField jTextFieldBarraBusqueda;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
